version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.13

  pre_build:
    commands:
      - echo "==============================="
      - echo "Starting Lambda validation..."
      - echo "==============================="

      - python -m py_compile lambda-validator/lambda_function.py
      - python -m py_compile lambda-etl/lambda_function.py
      - python -m py_compile lambda-audit/lambda_function.py

  build:
    commands:
      ################################################
      # Package Validator
      ################################################
      - echo "Packaging lambda-validator..."
      - rm -rf validator-build
      - mkdir -p validator-build
      - cp lambda-validator/lambda_function.py validator-build/
      - cp -r utils validator-build/
      - cd validator-build
      - zip -r ../validator.zip .
      - cd ..

      ################################################
      # Package ETL
      ################################################
      - echo "Packaging lambda-etl..."
      - rm -rf etl-build
      - mkdir -p etl-build
      - cp lambda-etl/lambda_function.py etl-build/
      - cp -r utils etl-build/
      - cd etl-build
      - zip -r ../etl.zip .
      - cd ..

      ################################################
      # Package Audit
      ################################################
      - echo "Packaging lambda-audit..."
      - rm -rf audit-build
      - mkdir -p audit-build
      - cp lambda-audit/lambda_function.py audit-build/
      - cp -r utils audit-build/
      - cd audit-build
      - zip -r ../audit.zip .
      - cd ..

  post_build:
    commands:
      - echo "==============================="
      - echo "Checking AWS CLI..."
      - echo "==============================="
      - aws --version

      ################################################
      # Deploy Validator
      ################################################
      - echo "Deploying lambda-validator..."
      - aws lambda update-function-code --function-name lambda-validator --zip-file fileb://validator.zip

      ################################################
      # Deploy ETL
      ################################################
      - echo "Deploying lambda-etl..."
      - aws lambda update-function-code --function-name lambda-etl --zip-file fileb://etl.zip

      ################################################
      # Deploy Audit
      ################################################
      - echo "Deploying lambda-audit..."
      - aws lambda update-function-code --function-name lambda-audit --zip-file fileb://audit.zip

      - echo "==============================="
      - echo "Deployment completed successfully!"
      - echo "==============================="

artifacts:
  files:
    - validator.zip
    - etl.zip
    - audit.zip
